### ISSUE TITLE
Business Fields to be mapped to SalesForce

### ISSUE THREAD

**Issue by kitsushadow** [jgodbout19/ecomanyatta#1]
What are the business fields that are going to be mapped into SalesForce

**Comment by jgodbout19** [comment]
Need an upload file feature

**Comment by jgodbout19** [comment]
Intial Data Capture Elements:
- Surname
- Given Names
- Mobile Number
- Email
- Location (Google API)
- Size of plot
- Number of homes on plot
- Land Registry Number
- Water Access? (Y/N)
- Electricity Access? (Y/N)
- Type of Cooking Stove
- Number of People living on Homestead
- Number of Children
- Loan or Self Funded?
- Desired Start Date

**Comment by JohnHillegass** [comment]
HTML for form :

Click edit on next comment to view

**Comment by JohnHillegass** [comment]
<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">





<form action="https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST">

<input type=hidden name="oid" value="00D15000000NRAX">
<input type=hidden name="retURL" value="http://placeholder.com">









<label for="first_name">First Name</label><input  id="first_name" maxlength="40" name="first_name" size="20" type="text" /><br>

<label for="last_name">Last Name</label><input  id="last_name" maxlength="80" name="last_name" size="20" type="text" /><br>

<label for="email">Email</label><input  id="email" maxlength="80" name="email" size="20" type="text" /><br>

<label for="company">Company</label><input  id="company" maxlength="40" name="company" size="20" type="text" /><br>

Mobile Number:<input  id="00N1500000II3cI" maxlength="40" name="00N1500000II3cI" onkeydown="formatPhoneOnEnter(this, event);" size="20" type="text" /><br>

Email:<input  id="00N1500000II3cS" maxlength="80" name="00N1500000II3cS" size="20" type="text" /><br>

Location (Google API) (Latitude):<input  id="0BC15000000Cg3j" name="0BC15000000Cg3j" size="20" type="text" /><br>

Location (Google API) (Longitude):<input  id="0BC15000000Cg3k" name="0BC15000000Cg3k" size="20" type="text" /><br>

Size of plot:<input  id="00N1500000II3cm" name="00N1500000II3cm" size="20" type="text" /><br>

Number of homes on plot:<input  id="00N1500000II3cw" name="00N1500000II3cw" size="20" type="text" /><br>

Land Registry Number:<input  id="00N1500000II3d1" name="00N1500000II3d1" size="20" type="text" /><br>

Water Access?:<select  id="00N1500000II3d6" name="00N1500000II3d6" title="Water Access?"><option value="">--None--</option><option value="Yes">Yes</option>
<option value="No">No</option>
<option value="In Progress">In Progress</option>
</select><br>

Electricity Access?:<select  id="00N1500000II3dB" name="00N1500000II3dB" title="Electricity Access?"><option value="">--None--</option><option value="Yes">Yes</option>
<option value="No">No</option>
<option value="In Progress">In Progress</option>
</select><br>

Type of Cooking Stove:<select  id="00N1500000II3dG" name="00N1500000II3dG" title="Type of Cooking Stove"><option value="">--None--</option><option value="Stove 1">Stove 1</option>
<option value="Stove 2">Stove 2</option>
</select><br>

Number of People living on Homestead:<input  id="00N1500000II3dL" name="00N1500000II3dL" size="20" type="text" /><br>

Number of Children:<input  id="00N1500000II3dQ" name="00N1500000II3dQ" size="20" type="text" /><br>

Loan or Self Funded?:<select  id="00N1500000II3dV" name="00N1500000II3dV" title="Loan or Self Funded?"><option value="">--None--</option><option value="Loan">Loan</option>
<option value="Self Funded">Self Funded</option>
</select><br>

Desired Start Date:<span class="dateInput dateOnlyInput"><input  id="00N1500000II3da" name="00N1500000II3da" size="12" type="text" /></span><br>

<input type="submit" name="submit">

</form>

**Comment by JohnHillegass** [comment]
<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">







<form action="https://www.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST">
<input type=hidden name="oid" value="00D15000000NRAX">
<input type=hidden name="retURL" value="http://placeholder.com">







<label for="first_name">First Name</label><input  id="first_name" maxlength="40" name="first_name" size="20" type="text" /><br>
<label for="last_name">Last Name</label><input  id="last_name" maxlength="80" name="last_name" size="20" type="text" /><br>
<label for="email">Email</label><input  id="email" maxlength="80" name="email" size="20" type="text" /><br>
<label for="company">Company</label><input  id="company" maxlength="40" name="company" size="20" type="text" /><br>
Mobile Number:<input  id="00N1500000II3cI" maxlength="40" name="00N1500000II3cI" onkeydown="formatPhoneOnEnter(this, event);" size="20" type="text" /><br>
Email:<input  id="00N1500000II3cS" maxlength="80" name="00N1500000II3cS" size="20" type="text" /><br>
Location (Google API) (Latitude):<input  id="0BC15000000Cg3j" name="0BC15000000Cg3j" size="20" type="text" /><br>
Location (Google API) (Longitude):<input  id="0BC15000000Cg3k" name="0BC15000000Cg3k" size="20" type="text" /><br>
Size of plot:<input  id="00N1500000II3cm" name="00N1500000II3cm" size="20" type="text" /><br>
Number of homes on plot:<input  id="00N1500000II3cw" name="00N1500000II3cw" size="20" type="text" /><br>
Land Registry Number:<input  id="00N1500000II3d1" name="00N1500000II3d1" size="20" type="text" /><br>
Water Access?:<select  id="00N1500000II3d6" name="00N1500000II3d6" title="Water Access?"><option value="">--None--</option><option value="Yes">Yes</option>
<option value="No">No</option>
<option value="In Progress">In Progress</option>
</select><br>
Electricity Access?:<select  id="00N1500000II3dB" name="00N1500000II3dB" title="Electricity Access?"><option value="">--None--</option><option value="Yes">Yes</option>
<option value="No">No</option>
<option value="In Progress">In Progress</option>
</select><br>
Type of Cooking Stove:<select  id="00N1500000II3dG" name="00N1500000II3dG" title="Type of Cooking Stove"><option value="">--None--</option><option value="Stove 1">Stove 1</option>
<option value="Stove 2">Stove 2</option>
</select><br>
Number of People living on Homestead:<input  id="00N1500000II3dL" name="00N1500000II3dL" size="20" type="text" /><br>
Number of Children:<input  id="00N1500000II3dQ" name="00N1500000II3dQ" size="20" type="text" /><br>
Loan or Self Funded?:<select  id="00N1500000II3dV" name="00N1500000II3dV" title="Loan or Self Funded?"><option value="">--None--</option><option value="Loan">Loan</option>
<option value="Self Funded">Self Funded</option>
</select><br>
Desired Start Date:<span class="dateInput dateOnlyInput"><input  id="00N1500000II3da" name="00N1500000II3da" size="12" type="text" /></span><br>
<input type="submit" name="submit">
</form>

**Comment by JohnHillegass** [comment]
Business fields mapped on the html form and on the salesfore lead and opportunities object
